### PR TITLE
[tests-only] Run CI on drone

### PR DESCRIPTION
**Pull request by phil-davis**
Fixes issue #25

### CODE REVIEW

**Review by karakayasemi — APPROVED** [review]
Thank you for taking care.

**Comment by phil-davis** [comment]
`continuous-integration/travis-ci` needs to be set to "not required"

@karakayasemi do you have privs to change that in the repo settings?

**Comment by karakayasemi** [comment]
Unfortunately, I have not enough privilege also.

**Comment by phil-davis** [comment]
"ERROR: You're not authorized to run analysis. Please contact the project administrator."
https://drone.owncloud.com/owncloud/twofactor_backup_codes/4/8/7
I need to add `sonar_token` to the drone secrets.

**Comment by phil-davis** [comment]
`sonar_token` has been added. I restarted drone https://drone.owncloud.com/owncloud/twofactor_backup_codes/5 - let's see what it says.

**Pull request merged**
